# Generated by Django 5.2.7 on 2025-10-29 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.ImageField(upload_to='uploads/')),
                ('processed', models.ImageField(blank=True, null=True, upload_to='processed/')),
                ('num_faces', models.IntegerField(default=0)),
                ('blur_level', models.FloatField(default=0.0)),
                ('is_blurry', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
